### ISSUE TITLE
Not returning a ball position when resolving deflections

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#44]
```
Error:  TypeError: Cannot read property 'map' of undefined
    at resolveDeflection (/Users/.../footballsimulationengine/lib/ballMovement.js:387:43)
    at resolveBallMovement (/Users/.../footballsimulationengine/lib/ballMovement.js:297:24)
    at Object.ballPassed (/Users/...l/footballsimulationengine/lib/ballMovement.js:488:16)
    at Object.decideMovement (/Users/.../footballsimulationengine/lib/playerMovement.js:183:42)
    at Object.playIteration (/Users/.../footballsimulationengine/engine.js:52:31)
    at /Users/.../footballsimulationexample/server.js:64:17
```

**Comment by GallagherAiden** [comment]
https://github.com/GallagherAiden/footballSimulationEngine/commit/44e5d3aefc668b4d2bb94f8edebca45b97bf2398
