### ISSUE TITLE
Error setting ball position after deflection

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#55]
(node:8693) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at resolveDeflection (/Users/aideng/Documents/football/footballsimulationengine/lib/ballMovement.js:387:43)
    at resolveBallMovement (/Users/aideng/Documents/football/footballsimulationengine/lib/ballMovement.js:297:24)
    at Object.ballKicked (/Users/aideng/Documents/football/footballsimulationengine/lib/ballMovement.js:109:16)
    at Object.decideMovement (/Users/aideng/Documents/football/footballsimulationengine/lib/playerMovement.js:177:42)

**Comment by GallagherAiden** [comment]
https://github.com/GallagherAiden/footballSimulationEngine/commit/44e5d3aefc668b4d2bb94f8edebca45b97bf2398
