### ISSUE TITLE
Players not on pitch after free kick setup

### ISSUE THREAD

**Issue by GallagherAiden** [GallagherAiden/footballSimulationEngine#58]
[ 'Closest Player to ball: Arthur Johnson',
  'Closest Player to ball: Emma Smith',
  'Slide tackle attempted by: Arthur Johnson',
  'Foul against: Emma Smith',
  'freekick to: ThisTeam' ]
(node:19569) UnhandledPromiseRejectionWarning: Error: Player Peter Johnson not on the pitch Y: -61
    at Object.validatePlayerPositions (/Users/aideng/Documents/football/footballsimulationengine/lib/validate.js:145:13)
    at Object.playIteration (/Users/aideng/Documents/football/footballsimulationengine/engine.js:43:12)
    at iterateHalf (/Users/aideng/Documents/football/premierLeagueSimulator/completeMatch.js:31:42)
(node:19569) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GallagherAiden** [comment]
https://github.com/GallagherAiden/footballSimulationEngine/commit/0d3b45c727c0fcdf89cdeb8449c7bbee7c4dfe61
https://github.com/GallagherAiden/footballSimulationEngine/commit/6a0e97c89c54a85b6af7eb251939d11d1363aff9
